package dev.abelab.timestamp.db.entity;

import java.util.Date;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class StampAttachment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stamp_attachment.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stamp_attachment.stamp_id
     *
     * @mbg.generated
     */
    private Integer stampId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stamp_attachment.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stamp_attachment.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stamp_attachment.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stamp_attachment.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;
}