package dev.abelab.timestamp.db.mapper.base;

import dev.abelab.timestamp.db.entity.Stamp;
import dev.abelab.timestamp.db.entity.StampExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface StampBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamp
     *
     * @mbg.generated
     */
    long countByExample(StampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamp
     *
     * @mbg.generated
     */
    int deleteByExample(StampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamp
     *
     * @mbg.generated
     */
    int insert(Stamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamp
     *
     * @mbg.generated
     */
    int insertSelective(Stamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamp
     *
     * @mbg.generated
     */
    List<Stamp> selectByExampleWithBLOBs(StampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamp
     *
     * @mbg.generated
     */
    List<Stamp> selectByExample(StampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamp
     *
     * @mbg.generated
     */
    Stamp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamp
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Stamp record, @Param("example") StampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamp
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Stamp record, @Param("example") StampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamp
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Stamp record, @Param("example") StampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Stamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Stamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stamp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Stamp record);
}